name: End-to-end tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    name: Run tests
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel_cypress_testing
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Run composer
        run: composer update --no-interaction --no-progress  --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Configuration caching for speed
        run: php artisan config:cache

      - name: Route caching for speed
        run: php artisan route:cache

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Migrate
        run: php artisan migrate

      - uses: cypress-io/github-action@v6
        with:
          start: |
            npm run build
            npm run server
            npm run cy:run:ci
          wait-on: 'http://127.0.0.1:8000'

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
